import {Economy,reward,medal,payout} from './aura-economy.mjs';
const $=s=>document.querySelector(s), users=[{id:'maya',name:'Maya',role:'debater',host:true,admin:true,score:77},{id:'jordan',name:'Jordan',role:'debater',score:92},{id:'alex',name:'Alex',role:'spectator'},{id:'sam',name:'Sam',role:'spectator'},{id:'lee',name:'Lee',role:'spectator'}].map(u=>({...u,balance:100000,present:true}));
const economy=new Economy(users);let offset=0,room=false;const now=()=>Date.now()+offset,active=()=>$('#account').value;
$('#account').innerHTML=users.map(u=>`<option value="${u.id}" ${u.id==='alex'?'selected':''}>${u.name}</option>`).join('');
function render(){economy.tick(now());const u=economy.user(active());$('#balance').textContent=u.balance.toLocaleString()+' Aura · '+u.role;$('#view').textContent=room?'Debate room':'Dashboard / scheduled debate';$('#phase').textContent=economy.phase==='countdown'?'Place your stakes · '+Math.max(0,Math.ceil((economy.countdownEnd-now())/1000))+' seconds':economy.phase+(economy.endAt?' · Appeal deadline '+new Date(economy.endAt+7*86400000).toLocaleString():'');$('#pool').textContent='Reserved pool: '+economy.bets.reduce((n,b)=>n+b.stake,0)+' Aura from '+economy.bets.length+' accounts';const b=economy.bets.find(b=>b.user===u.id);$('#my-bet').textContent=b?'Your stake: '+b.stake+' on '+b.side:'No stake placed.';$('#side').disabled=!!b;if(b)$('#side').value=b.side;
$('#controls').replaceChildren();if(u.host&&u.admin){for(const [key,label] of [['effects','Aura gifts'],['betting','Aura farming']]){const button=document.createElement('button');button.textContent=(economy[key]?'Disable ':'Enable ')+label;button.onclick=()=>run(()=>economy.control(u.id,key,!economy[key]));$('#controls').append(button)}}
$('#gift').disabled=!economy.effects||u.role!=='spectator';$('#bet').disabled=!economy.betting||economy.audience||!['lobby','countdown'].includes(economy.phase)||u.role!=='spectator'||u.host;$('#join').disabled=u.role!=='spectator'||economy.phase!=='lobby';$('#medal-maya').textContent=medal(77);$('#medal-jordan').textContent=medal(92);$('#ledger').textContent=JSON.stringify(economy.log,null,2);$('#collection').textContent=economy.orders.filter(o=>o.user===u.id).map(o=>o.item+' · '+o.status).join(' / ')||'No stickers or requests yet.';audit()}
function audit(){const errors=economy.audit().filter(r=>!r.ok);$('#audit').textContent=errors.length?'Discrepancy detected: '+JSON.stringify(errors):'Reconciled: every wallet matches its transaction log.'}
function run(fn){try{fn();$('#status').textContent='Updated test state.'}catch(e){$('#status').textContent=e.message}render()}
$('#account').onchange=render;$('#theme').onclick=()=>document.body.classList.toggle('light');$('#reset').onclick=()=>location.reload();$('#location').onclick=()=>{room=!room;render()};$('#bet').onclick=()=>run(()=>economy.bet(active(),$('#side').value,Number($('#stake').value),now()));$('#gift').onclick=()=>run(()=>{const recipient=$('#recipient').value;economy.gift(active(),recipient);const el=document.createElement('span');el.className='effect';el.textContent=$('#effect').value.split(' ')[0]+' +1';document.querySelector('[data-person="'+recipient+'"]').append(el);setTimeout(()=>el.remove(),2000)});$('#join').onclick=()=>run(()=>economy.joinDebater(active()));
$('#present').onchange=()=>run(()=>{const n=Number($('#present').value);if(!Number.isInteger(n)||n<0||n>3)throw Error('Choose 0–3');economy.users.filter(u=>u.role==='spectator').forEach((u,i)=>u.present=i<n)});
$('#audience').onchange=()=>run(()=>{economy.audience=$('#audience').checked;if(economy.audience)for(const b of [...economy.bets])economy.refund(b.user)});$('#pending').onchange=()=>{economy.appealPending=$('#pending').checked};$('#start').onclick=()=>run(()=>economy.start(now()));$('#advance').onclick=()=>run(()=>{offset+=30000;economy.tick(now())});$('#end').onclick=()=>run(()=>economy.end(now()));$('#week').onclick=()=>run(()=>{offset+=7*86400000});$('#settle').onclick=()=>run(()=>economy.settle($('#winner').value,now()));$('#cancel').onclick=()=>run(()=>economy.cancel());
$('#example').onclick=()=>{$('#example-output').textContent=JSON.stringify(payout([{user:'winner',stake:1,side:'PRO'},...Array.from({length:9},(_,i)=>({user:'loser'+(i+1),stake:20,side:'CON'}))],'PRO'),null,2)};
function inputs(){return {score:Number($('#score').value),won:$('#won').value==='true',mode:$('#mode').value,botLevel:Number($('#level').value),ownRank:77,opponentRank:Number($('#opponent').value),teamSize:Number($('#team').value)}}
$('#reward-preview').onclick=()=>run(()=>{$('#reward-result').textContent=JSON.stringify(reward(inputs()),null,2)});$('#award').onclick=()=>run(()=>{$('#reward-result').textContent=JSON.stringify(economy.award('maya','demo-result',inputs()),null,2)});
const catalog=[{name:'Retro emulation handheld',price:50000,url:'https://anbernic.com/products/rg35xx-plus',note:'Candidate: RG35XX Plus. Confirm under-$50 variant and availability.'},{name:'Nike T-shirt',price:35000,url:'https://www.nike.com/gb/t/sportswear-club-t-shirt-bVD3j8/AR4997-013',note:'Size choice; confirm local price.'},{name:'Designer mug',price:25000,url:'https://www.marimekko.com/us_en/063431-001',note:'Confirm design and under-$50 price.'},{name:'LICAEVEY 5-inch reader / writing tablet',price:50000,url:'https://www.amazon.com/dp/B0GC4FPH35',image:'assets/rewards/licaevey-reader.jpg',note:'Listed at $49.56 in the supplied Amazon snapshot. Seller describes pen and note-taking support; specifications, stock, tax and shipping need verification.'}];
for(const item of catalog){const card=document.createElement('article');card.className='card';const heading=document.createElement('h3');heading.textContent=item.name;const photo=item.image||(item.name==='Retro emulation handheld'?'https://anbernic.com/cdn/shop/files/RG35XX_b647f51d-9e8a-4d4a-b8a4-17dcb7a1ab41.jpg?v=1756540825&width=800':item.name==='Nike T-shirt'?'https://content.stylitics.com/images/items/8252259':null);if(photo){const img=document.createElement('img');img.src=photo;img.alt=item.name;img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>img.remove();card.append(img)}const note=document.createElement('p');note.textContent=item.note;const price=document.createElement('p');price.textContent=item.price.toLocaleString()+' Aura · draft price';const link=document.createElement('a');link.href=item.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Product reference / photos';const button=document.createElement('button');button.textContent='Preview gift request';button.onclick=()=>checkout(item);card.append(heading,note,price,link,button);$('#catalog').append(card)}
for(const [name,price] of [['♥ Good point',20],['★ Clear thinker',40],['ϟ Quick rebuttal',60]]){const b=document.createElement('button');b.textContent=name+' · '+price+' Aura';b.onclick=()=>run(()=>economy.purchase(active(),name,price,'sticker-'+active()+'-'+name));$('#stickers').append(b)}
let selected=null,step=0,owner=null,request=null;const dialog=$('#checkout'),form=$('#checkout-form');
function checkout(item){selected=item;owner=active();request=crypto.randomUUID();step=0;form.reset();$('#checkout-title').textContent=item.name;$('#address').hidden=false;$('#size-label').hidden=item.name!=='Nike T-shirt';$('#order-review').hidden=true;$('#order-back').hidden=true;$('#order-next').textContent='Review details';dialog.showModal()}
$('#order-cancel').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{form.reset();$('#order-review').textContent='';selected=null});$('#order-back').onclick=()=>{step=0;$('#address').hidden=false;$('#order-review').hidden=true;$('#order-back').hidden=true;$('#order-next').textContent='Review details'};
form.onsubmit=e=>{e.preventDefault();if(step===0){const data=new FormData(form);$('#order-review').textContent='Confirmation 1 / 2 — Recipient\n'+selected.name+'\n'+['recipient','street','city','region','postal','country'].map(k=>data.get(k)).join('\n')+(selected.name==='Nike T-shirt'?'\nSize: '+data.get('size'):'');$('#address').hidden=true;$('#order-review').hidden=false;$('#order-back').hidden=false;$('#order-next').textContent='Confirm recipient';step=1}else if(step===1){$('#order-review').textContent+='\n\nConfirmation 2 / 2 — Spend '+selected.price+' demo Aura\nRemaining balance: '+(economy.user(owner).balance-selected.price)+'\nNo shipment or real order. Address will be discarded.';$('#order-next').textContent='Confirm demo redemption';step=2}else{try{economy.purchase(owner,selected.name,selected.price,request);dialog.close();$('#status').textContent='Demo request recorded. No address saved or shipment requested.';render()}catch(error){$('#order-review').textContent=error.message;$('#order-back').hidden=false}}};
render();setInterval(()=>{if(economy.phase==='countdown')render()},250);setInterval(audit,5000);
